[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateSet('Initialize', 'Adopt', 'Find', 'Supersede', 'Invalidate', 'Validate')]
    [string] $Action,

    [Parameter(Mandatory)]
    [string] $ProjectRoot,

    [string] $Id,
    [ValidateSet('decision', 'verified-fact', 'interface', 'unresolved-risk')]
    [string] $Type,
    [string] $Summary,
    [string[]] $Tags = @(),
    [string[]] $SourceRefs = @(),
    [string] $Supersedes,
    [string] $Query,
    [ValidateRange(1, 5)]
    [int] $Limit = 5,
    [switch] $RefreshStale
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$root = (Resolve-Path -LiteralPath $ProjectRoot).Path.TrimEnd('\', '/')
$knowledgeRoot = Join-Path $root '.orchestrator\knowledge'
$catalogPath = Join-Path $knowledgeRoot 'catalog.json'
$indexPath = Join-Path $knowledgeRoot 'INDEX.md'

function Save-Catalog {
    param([object] $Catalog)

    $Catalog | ConvertTo-Json -Depth 20 |
        Set-Content -LiteralPath $catalogPath -Encoding utf8
    $lines = [Collections.Generic.List[string]]::new()
    $lines.Add('# Project knowledge')
    $lines.Add('')
    $lines.Add('Generated from `catalog.json`. Do not edit this file manually.')
    $lines.Add('')
    foreach ($entry in @($Catalog.entries | Sort-Object id)) {
        $tagsText = if (@($entry.tags).Count) {
            ' [' + (@($entry.tags) -join ', ') + ']'
        } else { '' }
        $lines.Add("## $($entry.id)")
        $lines.Add('')
        $lines.Add("- Type/status: $($entry.type) / $($entry.status)$tagsText")
        $lines.Add("- Summary: $($entry.summary)")
        $lines.Add("- Sources: $(@($entry.sources | ForEach-Object { $_.ref }) -join '; ')")
        if (-not [string]::IsNullOrWhiteSpace([string]$entry.supersedes)) {
            $lines.Add("- Supersedes: $($entry.supersedes)")
        }
        $lines.Add('')
    }
    $lines | Set-Content -LiteralPath $indexPath -Encoding utf8
}

function Get-Catalog {
    if (-not (Test-Path -LiteralPath $catalogPath -PathType Leaf)) {
        throw "Project knowledge is not initialized: $catalogPath"
    }
    return Get-Content -LiteralPath $catalogPath -Raw |
        ConvertFrom-Json -Depth 20
}

function Resolve-Source {
    param([string] $Reference)

    if ([string]::IsNullOrWhiteSpace($Reference)) {
        throw 'Source references cannot be empty.'
    }
    if ($Reference -match '^path:(.+)$') {
        $relative = $Matches[1]
        if ([IO.Path]::IsPathRooted($relative) -or
            ($relative -split '[\\/]' -contains '..')) {
            throw "Unsafe project source reference: $Reference"
        }
        $path = [IO.Path]::GetFullPath((Join-Path $root $relative))
        if (-not $path.StartsWith(
            $root + [IO.Path]::DirectorySeparatorChar,
            [StringComparison]::OrdinalIgnoreCase
        )) {
            throw "Project source escapes the root: $Reference"
        }
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
            throw "Project source does not exist: $Reference"
        }
        return [pscustomobject]@{
            ref = $Reference
            sha256 = (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()
        }
    }
    if ($Reference -notmatch '^(source|artifact|url):\S') {
        throw "Source reference must start with path:, source:, artifact:, or url:: $Reference"
    }
    return [pscustomobject]@{ ref = $Reference; sha256 = $null }
}

if ($Action -eq 'Initialize') {
    if (Test-Path -LiteralPath $catalogPath) {
        throw "Project knowledge already exists: $catalogPath"
    }
    $null = New-Item -ItemType Directory -Path $knowledgeRoot -Force
    $catalog = [pscustomobject]@{
        schema_version = '1.0'
        entries = @()
    }
    Save-Catalog $catalog
    [pscustomobject]@{
        initialized = $true
        catalog_path = $catalogPath
        index_path = $indexPath
    } | ConvertTo-Json
    exit 0
}

$catalog = Get-Catalog
if ($catalog.schema_version -ne '1.0') {
    throw "Unsupported project knowledge schema: $($catalog.schema_version)"
}
$entries = @($catalog.entries)
$duplicateIds = @($entries | Group-Object id | Where-Object Count -gt 1)
if ($duplicateIds.Count) {
    throw "Duplicate project knowledge ID: $($duplicateIds[0].Name)"
}

if ($Action -in @('Adopt', 'Supersede')) {
    if ($Id -notmatch '^[a-z0-9]+(?:-[a-z0-9]+)*$') {
        throw 'Knowledge Id must be lowercase hyphen-case.'
    }
    if ([string]::IsNullOrWhiteSpace($Type) -or
        [string]::IsNullOrWhiteSpace($Summary)) {
        throw "$Action requires Type and Summary."
    }
    if ($SourceRefs.Count -eq 0) {
        throw "$Action requires at least one SourceRefs entry."
    }
    if (@($entries | Where-Object id -eq $Id).Count) {
        throw "Knowledge ID already exists: $Id"
    }
    if ($Action -eq 'Supersede') {
        if ([string]::IsNullOrWhiteSpace($Supersedes)) {
            throw 'Supersede requires -Supersedes.'
        }
        $old = @($entries | Where-Object id -eq $Supersedes) |
            Select-Object -First 1
        if ($null -eq $old) {
            throw "Superseded knowledge ID does not exist: $Supersedes"
        }
        $old.status = 'superseded'
    } elseif (-not [string]::IsNullOrWhiteSpace($Supersedes)) {
        throw 'Adopt cannot set -Supersedes; use Action Supersede.'
    }
    $entry = [pscustomobject]@{
        id = $Id
        type = $Type
        status = 'adopted'
        summary = $Summary.Trim()
        tags = @($Tags | ForEach-Object { $_.Trim().ToLowerInvariant() } |
            Where-Object { $_ } | Select-Object -Unique)
        sources = @($SourceRefs | ForEach-Object { Resolve-Source $_ })
        verified_at = [DateTime]::UtcNow.ToString('o')
        supersedes = if ($Action -eq 'Supersede') { $Supersedes } else { $null }
    }
    $catalog.entries = @($entries) + $entry
    Save-Catalog $catalog
    $entry | ConvertTo-Json -Depth 10
    exit 0
}

if ($Action -eq 'Invalidate') {
    $entry = @($entries | Where-Object id -eq $Id) | Select-Object -First 1
    if ($null -eq $entry) { throw "Knowledge ID does not exist: $Id" }
    $entry.status = 'invalid'
    Save-Catalog $catalog
    $entry | ConvertTo-Json -Depth 10
    exit 0
}

$staleIds = [Collections.Generic.List[string]]::new()
foreach ($entry in $entries) {
    if ($entry.status -ne 'adopted') { continue }
    foreach ($source in @($entry.sources)) {
        if ([string]$source.ref -notmatch '^path:(.+)$') { continue }
        $relative = $Matches[1]
        $path = [IO.Path]::GetFullPath((Join-Path $root $relative))
        $currentHash = if (Test-Path -LiteralPath $path -PathType Leaf) {
            (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()
        } else { $null }
        if ([string]::IsNullOrWhiteSpace($currentHash) -or
            $currentHash -ne [string]$source.sha256) {
            $staleIds.Add([string]$entry.id)
            if ($RefreshStale) { $entry.status = 'stale' }
            break
        }
    }
}

if ($Action -eq 'Validate') {
    if ($RefreshStale -and $staleIds.Count) { Save-Catalog $catalog }
    [pscustomobject]@{
        valid = $staleIds.Count -eq 0
        entry_count = $entries.Count
        stale_ids = @($staleIds)
        refreshed = [bool]$RefreshStale
    } | ConvertTo-Json -Depth 10
    exit 0
}

$normalizedQuery = [string]$Query
$matches = @($entries | Where-Object {
    $_.status -eq 'adopted' -and (
        [string]::IsNullOrWhiteSpace($normalizedQuery) -or
        $_.id -like "*$normalizedQuery*" -or
        $_.type -like "*$normalizedQuery*" -or
        $_.summary -like "*$normalizedQuery*" -or
        @($_.tags | Where-Object { $_ -like "*$normalizedQuery*" }).Count
    )
} | Select-Object -First $Limit)
[pscustomobject]@{
    query = $normalizedQuery
    count = $matches.Count
    entries = $matches
} | ConvertTo-Json -Depth 10
